apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./virtual-machine.yaml
- ./service.yaml

patches:
- patch: |-
    apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: windows-10-vm
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: windows-10-vm-root
          spec:
            source:
              pvc:
                name: windows-10-base-l6bxm
