apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chrisj

resources:
- ./virtual-machine.yaml
- ./service.yaml

patches:
- patch: |-
    apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: windows-10-vm
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: windows-10-vm-root
          spec:
            pvc:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 20Gi
              storageClassName: ocs-storagecluster-cephfs
            source:
              pvc:
                name: windows-10-base-l6bxm
                namespace: chrisj
