apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: fedora
  namespace: openshift-gitops
spec:
  destination:
    namespace: vms
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vms/fedora
    repoURL: https://github.com/jkeam/ocp-virt.git
