kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ogaac-gitops-vms
  namespace: kubevirt-gitops
  labels:
    app.kubernetes.io/instance: openshift-virtualization
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-vms
