kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-vms
  namespace: kubevirt-gitops
  labels:
    app.kubernetes.io/instance: openshift-virtualization
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
