apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: httpd-server
  namespace: openshift-gitops
spec:
  destination:
    namespace: cluster-services
    server: https://kubernetes.default.svc
  project: default
  source:
    path: httpd-server/overlays/default
    repoURL: https://github.com/jkeam/ocp-virt.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
