kind: Secret
apiVersion: v1
metadata:
  name: git-secret
  namespace: chrisj
  annotations:
    tekton.dev/git-0: "https://github.com"
stringData:
  password: "REPLACE-ME-PAT"
  username: "REPLACE-ME-USERNAME"
type: kubernetes.io/basic-auth
